version: '3.1'

services:
  s_api_gateway:
    container_name: c_api_gateway
    image: kmlcn1/apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
      - 80:80
   

  s_contact_api:
    container_name: c_contact_api
    image: kmlcn1/contactapi
    build:
      context: .
      dockerfile: Services/ContactAPI/Contact.API/Dockerfile
    ports:
      - 9000:9000
  






